### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by hinok**
Hey,
I updated dependencies for `01-...` and `02-...` projects and removed deprecated packages (`autoprefixer-core` was replaced by `autoprefixer`) because right now `02-...` just doesn't work as npm cannot find `css-modulesify` package.

zrzut ekranu 2016-11-18 o 22 53 01

```
"css-modulesify": "git://github.com/css-modules/css-modulesify#postcss-after",
```

`postcss-after` branch was merged into `master` so I just updated it to the newest version, after that I had to update other `postcss-*` packages.

The only new problem that I found after update is a problem with css variables in `02-...` that are imported. Look at generated css

```css
._src_styles_media_item__description {
  font-style: italic;
  text-align: center;
  color: undefined;
  color: var(--text-color);
}
```

```css
  color: undefined;
```

It's a bit hard for me to find the root of the issue. I changed the order of postcss plugins so right now we have:

* postcss-import
* postcss-nested 
* postcss-css-variables (https://github.com/MadLittleMods/postcss-css-variables#nested-rules)

Added also `.babelrc` for instrumenting babelify.

If we fix `undefined` issue, PR could be merged and we'd have newest packages on the board.

### CODE REVIEW

**Comment by joshwnj** [comment]
Thanks @hinok , nice find! I'll take a look at that `undefined` issue, and then we can merge this.

**Comment by joshwnj** [comment]
@hinok I guess there were some breaking changes with the new major-version of those postcss plugins.

I've got it to work again by making the following 2 edits:

- https://github.com/x-team/starting-css-modules/pull/1/commits/e7be8950c43fbc787ed93dde82991d67fcb89857
- https://github.com/x-team/starting-css-modules/pull/1/commits/61f318179beec1a52c92a8a0e506c4ed962c0c54

Let me know if that fixes it for you too, then we can merge.  Thanks!

**Comment by hinok** [comment]
**Edit**

I pulled your commits and double check with fresh `npm install`, the problem is still there (look at red rectangle on the screenshot below).

zrzut ekranu 2016-11-24 o 10 27 03


---

Please kill me 🗡 , I wouldn't expect that changing

```
@import "./vars.css";
```
to
```
@import "vars.css";
```

could fix the problem. Thanks! I feel stupid 😛

**Comment by joshwnj** [comment]
Yeah it was a surprise to me too! :) I guess something changed the major-version bump. Will have to look into it because I'd much prefer "./vars.css" over "vars.css", for consistency with how node path resolution works.

**Pull request merged**
